version: '3.8'
services:

  app:
    volumes:
        - ./src/app:/app
    build:
        context: ./src
        dockerfile: app.dockerfile
        args:
          INSTALL_DEV: ${INSTALL_DEV-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /start-dev.sh